/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


@interface asdfAuthenticationEnvelope : NSObject <TBase, NSCoding> {
  NSString * __token;

  BOOL __token_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=token, setter=setToken:) NSString * token;
#endif

- (id) init;
- (id) initWithToken: (NSString *) token;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) token;
- (void) setToken: (NSString *) token;
#endif
- (BOOL) tokenIsSet;

@end

@interface asdfcapitalizationStruct : NSObject <TBase, NSCoding> {
  asdfAuthenticationEnvelope * __Token;
  NSString * __token;
  int32_t __toKen;

  BOOL __Token_isset;
  BOOL __token_isset;
  BOOL __toKen_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=token, setter=setToken:) asdfAuthenticationEnvelope * Token;
@property (nonatomic, retain, getter=token, setter=setToken:) NSString * token;
@property (nonatomic, getter=toKen, setter=setToKen:) int32_t toKen;
#endif

- (id) init;
- (id) initWithToken: (asdfAuthenticationEnvelope *) Token token: (NSString *) token toKen: (int32_t) toKen;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (asdfAuthenticationEnvelope *) token;
- (void) setToken: (asdfAuthenticationEnvelope *) Token;
#endif
- (BOOL) TokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) token;
- (void) setToken: (NSString *) token;
#endif
- (BOOL) tokenIsSet;

#if !__has_feature(objc_arc)
- (int32_t) toKen;
- (void) setToKen: (int32_t) toKen;
#endif
- (BOOL) toKenIsSet;

@end

@protocol asdfAuthenticatedService <NSObject>
- (int32_t) ping: (asdfAuthenticationEnvelope *) envelope;  // throws TException
@end

@interface asdfAuthenticatedServiceClient : TBaseClient <asdfAuthenticatedService> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface asdfAuthenticatedServiceProcessor : NSObject <TProcessor> {
  id <asdfAuthenticatedService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAuthenticatedService: (id <asdfAuthenticatedService>) service;
- (id<asdfAuthenticatedService>) service;
@end

@protocol asdfAuthenticatedService1 <NSObject>
- (int32_t) ping11: (asdfAuthenticationEnvelope *) envelope;  // throws TException
- (int32_t) ping12: (asdfAuthenticationEnvelope *) envelope;  // throws TException
@end

@interface asdfAuthenticatedService1Client : TBaseClient <asdfAuthenticatedService1> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface asdfAuthenticatedService1Processor : NSObject <TProcessor> {
id <asdfAuthenticatedService1> mService;
NSDictionary * mMethodMap;
}
- (id) initWithAuthenticatedService1: (id <asdfAuthenticatedService1>) service;
- (id<asdfAuthenticatedService1>) service;
@end

@protocol asdfAuthenticatedService2 <NSObject>
- (int32_t) ping21: (asdfAuthenticationEnvelope *) envelope;  // throws TException
- (int32_t) ping22: (asdfAuthenticationEnvelope *) envelope;  // throws TException
- (int32_t) ping23: (asdfAuthenticationEnvelope *) envelope;  // throws TException
@end

@interface asdfAuthenticatedService2Client : TBaseClient <asdfAuthenticatedService2> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface asdfAuthenticatedService2Processor : NSObject <TProcessor> {
id <asdfAuthenticatedService2> mService;
NSDictionary * mMethodMap;
}
- (id) initWithAuthenticatedService2: (id <asdfAuthenticatedService2>) service;
- (id<asdfAuthenticatedService2>) service;
@end

@interface asdfasdfConstants : NSObject {
}
@end
