/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


enum ThriftTestNumberz {
  Numberz_ONE = 1,
  Numberz_TWO = 2,
  Numberz_THREE = 3,
  Numberz_FIVE = 5,
  Numberz_SIX = 6,
  Numberz_EIGHT = 8
};

typedef int64_t ThriftTestUserId;

typedef NSMutableDictionary * ThriftTestMapType;

@interface ThriftTestBonk : NSObject <TBase, NSCoding> {
  NSString * __message;
  int32_t __type;

  BOOL __message_isset;
  BOOL __type_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, getter=type, setter=setType:) int32_t type;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message type: (int32_t) type;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (int32_t) type;
- (void) setType: (int32_t) type;
#endif
- (BOOL) typeIsSet;

@end

@interface ThriftTestBools : NSObject <TBase, NSCoding> {
  BOOL __im_true;
  BOOL __im_false;

  BOOL __im_true_isset;
  BOOL __im_false_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=im_true, setter=setIm_true:) BOOL im_true;
@property (nonatomic, getter=im_false, setter=setIm_false:) BOOL im_false;
#endif

- (id) init;
- (id) initWithIm_true: (BOOL) im_true im_false: (BOOL) im_false;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) im_true;
- (void) setIm_true: (BOOL) im_true;
#endif
- (BOOL) im_trueIsSet;

#if !__has_feature(objc_arc)
- (BOOL) im_false;
- (void) setIm_false: (BOOL) im_false;
#endif
- (BOOL) im_falseIsSet;

@end

@interface ThriftTestXtruct : NSObject <TBase, NSCoding> {
  NSString * __string_thing;
  uint8_t __byte_thing;
  int32_t __i32_thing;
  int64_t __i64_thing;

  BOOL __string_thing_isset;
  BOOL __byte_thing_isset;
  BOOL __i32_thing_isset;
  BOOL __i64_thing_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=string_thing, setter=setString_thing:) NSString * string_thing;
@property (nonatomic, getter=byte_thing, setter=setByte_thing:) uint8_t byte_thing;
@property (nonatomic, getter=i32_thing, setter=setI32_thing:) int32_t i32_thing;
@property (nonatomic, getter=i64_thing, setter=setI64_thing:) int64_t i64_thing;
#endif

- (id) init;
- (id) initWithString_thing: (NSString *) string_thing byte_thing: (uint8_t) byte_thing i32_thing: (int32_t) i32_thing i64_thing: (int64_t) i64_thing;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) string_thing;
- (void) setString_thing: (NSString *) string_thing;
#endif
- (BOOL) string_thingIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) byte_thing;
- (void) setByte_thing: (uint8_t) byte_thing;
#endif
- (BOOL) byte_thingIsSet;

#if !__has_feature(objc_arc)
- (int32_t) i32_thing;
- (void) setI32_thing: (int32_t) i32_thing;
#endif
- (BOOL) i32_thingIsSet;

#if !__has_feature(objc_arc)
- (int64_t) i64_thing;
- (void) setI64_thing: (int64_t) i64_thing;
#endif
- (BOOL) i64_thingIsSet;

@end

@interface ThriftTestXtruct2 : NSObject <TBase, NSCoding> {
  uint8_t __byte_thing;
  ThriftTestXtruct * __struct_thing;
  int32_t __i32_thing;

  BOOL __byte_thing_isset;
  BOOL __struct_thing_isset;
  BOOL __i32_thing_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=byte_thing, setter=setByte_thing:) uint8_t byte_thing;
@property (nonatomic, retain, getter=struct_thing, setter=setStruct_thing:) ThriftTestXtruct * struct_thing;
@property (nonatomic, getter=i32_thing, setter=setI32_thing:) int32_t i32_thing;
#endif

- (id) init;
- (id) initWithByte_thing: (uint8_t) byte_thing struct_thing: (ThriftTestXtruct *) struct_thing i32_thing: (int32_t) i32_thing;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (uint8_t) byte_thing;
- (void) setByte_thing: (uint8_t) byte_thing;
#endif
- (BOOL) byte_thingIsSet;

#if !__has_feature(objc_arc)
- (ThriftTestXtruct *) struct_thing;
- (void) setStruct_thing: (ThriftTestXtruct *) struct_thing;
#endif
- (BOOL) struct_thingIsSet;

#if !__has_feature(objc_arc)
- (int32_t) i32_thing;
- (void) setI32_thing: (int32_t) i32_thing;
#endif
- (BOOL) i32_thingIsSet;

@end

@interface ThriftTestXtruct3 : NSObject <TBase, NSCoding> {
  NSString * __string_thing;
  int32_t __changed;
  int32_t __i32_thing;
  int64_t __i64_thing;

  BOOL __string_thing_isset;
  BOOL __changed_isset;
  BOOL __i32_thing_isset;
  BOOL __i64_thing_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=string_thing, setter=setString_thing:) NSString * string_thing;
@property (nonatomic, getter=changed, setter=setChanged:) int32_t changed;
@property (nonatomic, getter=i32_thing, setter=setI32_thing:) int32_t i32_thing;
@property (nonatomic, getter=i64_thing, setter=setI64_thing:) int64_t i64_thing;
#endif

- (id) init;
- (id) initWithString_thing: (NSString *) string_thing changed: (int32_t) changed i32_thing: (int32_t) i32_thing i64_thing: (int64_t) i64_thing;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) string_thing;
- (void) setString_thing: (NSString *) string_thing;
#endif
- (BOOL) string_thingIsSet;

#if !__has_feature(objc_arc)
- (int32_t) changed;
- (void) setChanged: (int32_t) changed;
#endif
- (BOOL) changedIsSet;

#if !__has_feature(objc_arc)
- (int32_t) i32_thing;
- (void) setI32_thing: (int32_t) i32_thing;
#endif
- (BOOL) i32_thingIsSet;

#if !__has_feature(objc_arc)
- (int64_t) i64_thing;
- (void) setI64_thing: (int64_t) i64_thing;
#endif
- (BOOL) i64_thingIsSet;

@end

@interface ThriftTestInsanity : NSObject <TBase, NSCoding> {
  NSMutableDictionary * __userMap;
  NSMutableArray * __xtructs;

  BOOL __userMap_isset;
  BOOL __xtructs_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=userMap, setter=setUserMap:) NSMutableDictionary * userMap;
@property (nonatomic, retain, getter=xtructs, setter=setXtructs:) NSMutableArray * xtructs;
#endif

- (id) init;
- (id) initWithUserMap: (NSMutableDictionary *) userMap xtructs: (NSMutableArray *) xtructs;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) userMap;
- (void) setUserMap: (NSMutableDictionary *) userMap;
#endif
- (BOOL) userMapIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) xtructs;
- (void) setXtructs: (NSMutableArray *) xtructs;
#endif
- (BOOL) xtructsIsSet;

@end

@interface ThriftTestCrazyNesting : NSObject <TBase, NSCoding> {
  NSString * __string_field;
  NSMutableSet * __set_field;
  NSMutableArray * __list_field;
  NSData * __binary_field;

  BOOL __string_field_isset;
  BOOL __set_field_isset;
  BOOL __list_field_isset;
  BOOL __binary_field_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=string_field, setter=setString_field:) NSString * string_field;
@property (nonatomic, retain, getter=set_field, setter=setSet_field:) NSMutableSet * set_field;
@property (nonatomic, retain, getter=list_field, setter=setList_field:) NSMutableArray * list_field;
@property (nonatomic, retain, getter=binary_field, setter=setBinary_field:) NSData * binary_field;
#endif

- (id) init;
- (id) initWithString_field: (NSString *) string_field set_field: (NSMutableSet *) set_field list_field: (NSMutableArray *) list_field binary_field: (NSData *) binary_field;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) string_field;
- (void) setString_field: (NSString *) string_field;
#endif
- (BOOL) string_fieldIsSet;

#if !__has_feature(objc_arc)
- (NSMutableSet *) set_field;
- (void) setSet_field: (NSMutableSet *) set_field;
#endif
- (BOOL) set_fieldIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) list_field;
- (void) setList_field: (NSMutableArray *) list_field;
#endif
- (BOOL) list_fieldIsSet;

#if !__has_feature(objc_arc)
- (NSData *) binary_field;
- (void) setBinary_field: (NSData *) binary_field;
#endif
- (BOOL) binary_fieldIsSet;

@end

@interface ThriftTestXception : NSException <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __message;

  BOOL __errorCode_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface ThriftTestXception2 : NSException <TBase, NSCoding> {
  int32_t __errorCode;
  ThriftTestXtruct * __struct_thing;

  BOOL __errorCode_isset;
  BOOL __struct_thing_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=struct_thing, setter=setStruct_thing:) ThriftTestXtruct * struct_thing;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode struct_thing: (ThriftTestXtruct *) struct_thing;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (ThriftTestXtruct *) struct_thing;
- (void) setStruct_thing: (ThriftTestXtruct *) struct_thing;
#endif
- (BOOL) struct_thingIsSet;

@end

@interface ThriftTestEmptyStruct : NSObject <TBase, NSCoding> {
}

- (id) init;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

@end

@interface ThriftTestOneField : NSObject <TBase, NSCoding> {
  ThriftTestEmptyStruct * __field;

  BOOL __field_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=field, setter=setField:) ThriftTestEmptyStruct * field;
#endif

- (id) init;
- (id) initWithField: (ThriftTestEmptyStruct *) field;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ThriftTestEmptyStruct *) field;
- (void) setField: (ThriftTestEmptyStruct *) field;
#endif
- (BOOL) fieldIsSet;

@end

@interface ThriftTestVersioningTestV1 : NSObject <TBase, NSCoding> {
  int32_t __begin_in_both;
  NSString * __old_string;
  int32_t __end_in_both;

  BOOL __begin_in_both_isset;
  BOOL __old_string_isset;
  BOOL __end_in_both_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=begin_in_both, setter=setBegin_in_both:) int32_t begin_in_both;
@property (nonatomic, retain, getter=old_string, setter=setOld_string:) NSString * old_string;
@property (nonatomic, getter=end_in_both, setter=setEnd_in_both:) int32_t end_in_both;
#endif

- (id) init;
- (id) initWithBegin_in_both: (int32_t) begin_in_both old_string: (NSString *) old_string end_in_both: (int32_t) end_in_both;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) begin_in_both;
- (void) setBegin_in_both: (int32_t) begin_in_both;
#endif
- (BOOL) begin_in_bothIsSet;

#if !__has_feature(objc_arc)
- (NSString *) old_string;
- (void) setOld_string: (NSString *) old_string;
#endif
- (BOOL) old_stringIsSet;

#if !__has_feature(objc_arc)
- (int32_t) end_in_both;
- (void) setEnd_in_both: (int32_t) end_in_both;
#endif
- (BOOL) end_in_bothIsSet;

@end

@interface ThriftTestVersioningTestV2 : NSObject <TBase, NSCoding> {
  int32_t __begin_in_both;
  int32_t __newint;
  uint8_t __newbyte;
  int16_t __newshort;
  int64_t __newlong;
  double __newdouble;
  ThriftTestBonk * __newstruct;
  NSMutableArray * __newlist;
  NSMutableSet * __newset;
  NSMutableDictionary * __newmap;
  NSString * __newstring;
  int32_t __end_in_both;

  BOOL __begin_in_both_isset;
  BOOL __newint_isset;
  BOOL __newbyte_isset;
  BOOL __newshort_isset;
  BOOL __newlong_isset;
  BOOL __newdouble_isset;
  BOOL __newstruct_isset;
  BOOL __newlist_isset;
  BOOL __newset_isset;
  BOOL __newmap_isset;
  BOOL __newstring_isset;
  BOOL __end_in_both_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=begin_in_both, setter=setBegin_in_both:) int32_t begin_in_both;
@property (nonatomic, getter=newint, setter=setNewint:) int32_t newint;
@property (nonatomic, getter=newbyte, setter=setNewbyte:) uint8_t newbyte;
@property (nonatomic, getter=newshort, setter=setNewshort:) int16_t newshort;
@property (nonatomic, getter=newlong, setter=setNewlong:) int64_t newlong;
@property (nonatomic, getter=newdouble, setter=setNewdouble:) double newdouble;
@property (nonatomic, retain, getter=newstruct, setter=setNewstruct:) ThriftTestBonk * newstruct;
@property (nonatomic, retain, getter=newlist, setter=setNewlist:) NSMutableArray * newlist;
@property (nonatomic, retain, getter=newset, setter=setNewset:) NSMutableSet * newset;
@property (nonatomic, retain, getter=newmap, setter=setNewmap:) NSMutableDictionary * newmap;
@property (nonatomic, retain, getter=newstring, setter=setNewstring:) NSString * newstring;
@property (nonatomic, getter=end_in_both, setter=setEnd_in_both:) int32_t end_in_both;
#endif

- (id) init;
- (id) initWithBegin_in_both: (int32_t) begin_in_both newint: (int32_t) newint newbyte: (uint8_t) newbyte newshort: (int16_t) newshort newlong: (int64_t) newlong newdouble: (double) newdouble newstruct: (ThriftTestBonk *) newstruct newlist: (NSMutableArray *) newlist newset: (NSMutableSet *) newset newmap: (NSMutableDictionary *) newmap newstring: (NSString *) newstring end_in_both: (int32_t) end_in_both;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) begin_in_both;
- (void) setBegin_in_both: (int32_t) begin_in_both;
#endif
- (BOOL) begin_in_bothIsSet;

#if !__has_feature(objc_arc)
- (int32_t) newint;
- (void) setNewint: (int32_t) newint;
#endif
- (BOOL) newintIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) newbyte;
- (void) setNewbyte: (uint8_t) newbyte;
#endif
- (BOOL) newbyteIsSet;

#if !__has_feature(objc_arc)
- (int16_t) newshort;
- (void) setNewshort: (int16_t) newshort;
#endif
- (BOOL) newshortIsSet;

#if !__has_feature(objc_arc)
- (int64_t) newlong;
- (void) setNewlong: (int64_t) newlong;
#endif
- (BOOL) newlongIsSet;

#if !__has_feature(objc_arc)
- (double) newdouble;
- (void) setNewdouble: (double) newdouble;
#endif
- (BOOL) newdoubleIsSet;

#if !__has_feature(objc_arc)
- (ThriftTestBonk *) newstruct;
- (void) setNewstruct: (ThriftTestBonk *) newstruct;
#endif
- (BOOL) newstructIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) newlist;
- (void) setNewlist: (NSMutableArray *) newlist;
#endif
- (BOOL) newlistIsSet;

#if !__has_feature(objc_arc)
- (NSMutableSet *) newset;
- (void) setNewset: (NSMutableSet *) newset;
#endif
- (BOOL) newsetIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) newmap;
- (void) setNewmap: (NSMutableDictionary *) newmap;
#endif
- (BOOL) newmapIsSet;

#if !__has_feature(objc_arc)
- (NSString *) newstring;
- (void) setNewstring: (NSString *) newstring;
#endif
- (BOOL) newstringIsSet;

#if !__has_feature(objc_arc)
- (int32_t) end_in_both;
- (void) setEnd_in_both: (int32_t) end_in_both;
#endif
- (BOOL) end_in_bothIsSet;

@end

@interface ThriftTestListTypeVersioningV1 : NSObject <TBase, NSCoding> {
  NSMutableArray * __myints;
  NSString * __hello;

  BOOL __myints_isset;
  BOOL __hello_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=myints, setter=setMyints:) NSMutableArray * myints;
@property (nonatomic, retain, getter=hello, setter=setHello:) NSString * hello;
#endif

- (id) init;
- (id) initWithMyints: (NSMutableArray *) myints hello: (NSString *) hello;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) myints;
- (void) setMyints: (NSMutableArray *) myints;
#endif
- (BOOL) myintsIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hello;
- (void) setHello: (NSString *) hello;
#endif
- (BOOL) helloIsSet;

@end

@interface ThriftTestListTypeVersioningV2 : NSObject <TBase, NSCoding> {
  NSMutableArray * __strings;
  NSString * __hello;

  BOOL __strings_isset;
  BOOL __hello_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=strings, setter=setStrings:) NSMutableArray * strings;
@property (nonatomic, retain, getter=hello, setter=setHello:) NSString * hello;
#endif

- (id) init;
- (id) initWithStrings: (NSMutableArray *) strings hello: (NSString *) hello;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) strings;
- (void) setStrings: (NSMutableArray *) strings;
#endif
- (BOOL) stringsIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hello;
- (void) setHello: (NSString *) hello;
#endif
- (BOOL) helloIsSet;

@end

@interface ThriftTestGuessProtocolStruct : NSObject <TBase, NSCoding> {
  NSMutableDictionary * __map_field;

  BOOL __map_field_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=map_field, setter=setMap_field:) NSMutableDictionary * map_field;
#endif

- (id) init;
- (id) initWithMap_field: (NSMutableDictionary *) map_field;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) map_field;
- (void) setMap_field: (NSMutableDictionary *) map_field;
#endif
- (BOOL) map_fieldIsSet;

@end

@interface ThriftTestLargeDeltas : NSObject <TBase, NSCoding> {
  ThriftTestBools * __b1;
  ThriftTestBools * __b10;
  ThriftTestBools * __b100;
  BOOL __check_true;
  ThriftTestBools * __b1000;
  BOOL __check_false;
  ThriftTestVersioningTestV2 * __vertwo2000;
  NSMutableSet * __a_set2500;
  ThriftTestVersioningTestV2 * __vertwo3000;
  NSMutableArray * __big_numbers;

  BOOL __b1_isset;
  BOOL __b10_isset;
  BOOL __b100_isset;
  BOOL __check_true_isset;
  BOOL __b1000_isset;
  BOOL __check_false_isset;
  BOOL __vertwo2000_isset;
  BOOL __a_set2500_isset;
  BOOL __vertwo3000_isset;
  BOOL __big_numbers_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=b1, setter=setB1:) ThriftTestBools * b1;
@property (nonatomic, retain, getter=b10, setter=setB10:) ThriftTestBools * b10;
@property (nonatomic, retain, getter=b100, setter=setB100:) ThriftTestBools * b100;
@property (nonatomic, getter=check_true, setter=setCheck_true:) BOOL check_true;
@property (nonatomic, retain, getter=b1000, setter=setB1000:) ThriftTestBools * b1000;
@property (nonatomic, getter=check_false, setter=setCheck_false:) BOOL check_false;
@property (nonatomic, retain, getter=vertwo2000, setter=setVertwo2000:) ThriftTestVersioningTestV2 * vertwo2000;
@property (nonatomic, retain, getter=a_set2500, setter=setA_set2500:) NSMutableSet * a_set2500;
@property (nonatomic, retain, getter=vertwo3000, setter=setVertwo3000:) ThriftTestVersioningTestV2 * vertwo3000;
@property (nonatomic, retain, getter=big_numbers, setter=setBig_numbers:) NSMutableArray * big_numbers;
#endif

- (id) init;
- (id) initWithB1: (ThriftTestBools *) b1 b10: (ThriftTestBools *) b10 b100: (ThriftTestBools *) b100 check_true: (BOOL) check_true b1000: (ThriftTestBools *) b1000 check_false: (BOOL) check_false vertwo2000: (ThriftTestVersioningTestV2 *) vertwo2000 a_set2500: (NSMutableSet *) a_set2500 vertwo3000: (ThriftTestVersioningTestV2 *) vertwo3000 big_numbers: (NSMutableArray *) big_numbers;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ThriftTestBools *) b1;
- (void) setB1: (ThriftTestBools *) b1;
#endif
- (BOOL) b1IsSet;

#if !__has_feature(objc_arc)
- (ThriftTestBools *) b10;
- (void) setB10: (ThriftTestBools *) b10;
#endif
- (BOOL) b10IsSet;

#if !__has_feature(objc_arc)
- (ThriftTestBools *) b100;
- (void) setB100: (ThriftTestBools *) b100;
#endif
- (BOOL) b100IsSet;

#if !__has_feature(objc_arc)
- (BOOL) check_true;
- (void) setCheck_true: (BOOL) check_true;
#endif
- (BOOL) check_trueIsSet;

#if !__has_feature(objc_arc)
- (ThriftTestBools *) b1000;
- (void) setB1000: (ThriftTestBools *) b1000;
#endif
- (BOOL) b1000IsSet;

#if !__has_feature(objc_arc)
- (BOOL) check_false;
- (void) setCheck_false: (BOOL) check_false;
#endif
- (BOOL) check_falseIsSet;

#if !__has_feature(objc_arc)
- (ThriftTestVersioningTestV2 *) vertwo2000;
- (void) setVertwo2000: (ThriftTestVersioningTestV2 *) vertwo2000;
#endif
- (BOOL) vertwo2000IsSet;

#if !__has_feature(objc_arc)
- (NSMutableSet *) a_set2500;
- (void) setA_set2500: (NSMutableSet *) a_set2500;
#endif
- (BOOL) a_set2500IsSet;

#if !__has_feature(objc_arc)
- (ThriftTestVersioningTestV2 *) vertwo3000;
- (void) setVertwo3000: (ThriftTestVersioningTestV2 *) vertwo3000;
#endif
- (BOOL) vertwo3000IsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) big_numbers;
- (void) setBig_numbers: (NSMutableArray *) big_numbers;
#endif
- (BOOL) big_numbersIsSet;

@end

@interface ThriftTestNestedListsI32x2 : NSObject <TBase, NSCoding> {
  NSMutableArray * __integerlist;

  BOOL __integerlist_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=integerlist, setter=setIntegerlist:) NSMutableArray * integerlist;
#endif

- (id) init;
- (id) initWithIntegerlist: (NSMutableArray *) integerlist;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) integerlist;
- (void) setIntegerlist: (NSMutableArray *) integerlist;
#endif
- (BOOL) integerlistIsSet;

@end

@interface ThriftTestNestedListsI32x3 : NSObject <TBase, NSCoding> {
  NSMutableArray * __integerlist;

  BOOL __integerlist_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=integerlist, setter=setIntegerlist:) NSMutableArray * integerlist;
#endif

- (id) init;
- (id) initWithIntegerlist: (NSMutableArray *) integerlist;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) integerlist;
- (void) setIntegerlist: (NSMutableArray *) integerlist;
#endif
- (BOOL) integerlistIsSet;

@end

@interface ThriftTestNestedMixedx2 : NSObject <TBase, NSCoding> {
  NSMutableArray * __int_set_list;
  NSMutableDictionary * __map_int_strset;
  NSMutableArray * __map_int_strset_list;

  BOOL __int_set_list_isset;
  BOOL __map_int_strset_isset;
  BOOL __map_int_strset_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=int_set_list, setter=setInt_set_list:) NSMutableArray * int_set_list;
@property (nonatomic, retain, getter=map_int_strset, setter=setMap_int_strset:) NSMutableDictionary * map_int_strset;
@property (nonatomic, retain, getter=map_int_strset_list, setter=setMap_int_strset_list:) NSMutableArray * map_int_strset_list;
#endif

- (id) init;
- (id) initWithInt_set_list: (NSMutableArray *) int_set_list map_int_strset: (NSMutableDictionary *) map_int_strset map_int_strset_list: (NSMutableArray *) map_int_strset_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) int_set_list;
- (void) setInt_set_list: (NSMutableArray *) int_set_list;
#endif
- (BOOL) int_set_listIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) map_int_strset;
- (void) setMap_int_strset: (NSMutableDictionary *) map_int_strset;
#endif
- (BOOL) map_int_strsetIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) map_int_strset_list;
- (void) setMap_int_strset_list: (NSMutableArray *) map_int_strset_list;
#endif
- (BOOL) map_int_strset_listIsSet;

@end

@interface ThriftTestListBonks : NSObject <TBase, NSCoding> {
  NSMutableArray * __bonk;

  BOOL __bonk_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=bonk, setter=setBonk:) NSMutableArray * bonk;
#endif

- (id) init;
- (id) initWithBonk: (NSMutableArray *) bonk;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) bonk;
- (void) setBonk: (NSMutableArray *) bonk;
#endif
- (BOOL) bonkIsSet;

@end

@interface ThriftTestNestedListsBonk : NSObject <TBase, NSCoding> {
  NSMutableArray * __bonk;

  BOOL __bonk_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=bonk, setter=setBonk:) NSMutableArray * bonk;
#endif

- (id) init;
- (id) initWithBonk: (NSMutableArray *) bonk;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) bonk;
- (void) setBonk: (NSMutableArray *) bonk;
#endif
- (BOOL) bonkIsSet;

@end

@interface ThriftTestBoolTest : NSObject <TBase, NSCoding> {
  BOOL __b;
  NSString * __s;

  BOOL __b_isset;
  BOOL __s_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=b, setter=setB:) BOOL b;
@property (nonatomic, retain, getter=s, setter=setS:) NSString * s;
#endif

- (id) init;
- (id) initWithB: (BOOL) b s: (NSString *) s;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) b;
- (void) setB: (BOOL) b;
#endif
- (BOOL) bIsSet;

#if !__has_feature(objc_arc)
- (NSString *) s;
- (void) setS: (NSString *) s;
#endif
- (BOOL) sIsSet;

@end

@interface ThriftTestStructA : NSObject <TBase, NSCoding> {
  NSString * __s;

  BOOL __s_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=s, setter=setS:) NSString * s;
#endif

- (id) init;
- (id) initWithS: (NSString *) s;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) s;
- (void) setS: (NSString *) s;
#endif
- (BOOL) sIsSet;

@end

@interface ThriftTestStructB : NSObject <TBase, NSCoding> {
  ThriftTestStructA * __aa;
  ThriftTestStructA * __ab;

  BOOL __aa_isset;
  BOOL __ab_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=aa, setter=setAa:) ThriftTestStructA * aa;
@property (nonatomic, retain, getter=ab, setter=setAb:) ThriftTestStructA * ab;
#endif

- (id) init;
- (id) initWithAa: (ThriftTestStructA *) aa ab: (ThriftTestStructA *) ab;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ThriftTestStructA *) aa;
- (void) setAa: (ThriftTestStructA *) aa;
#endif
- (BOOL) aaIsSet;

#if !__has_feature(objc_arc)
- (ThriftTestStructA *) ab;
- (void) setAb: (ThriftTestStructA *) ab;
#endif
- (BOOL) abIsSet;

@end

@protocol ThriftTestThriftTest <NSObject>
- (void) testVoid;  // throws TException
- (NSString *) testString: (NSString *) thing;  // throws TException
- (uint8_t) testByte: (uint8_t) thing;  // throws TException
- (int32_t) testI32: (int32_t) thing;  // throws TException
- (int64_t) testI64: (int64_t) thing;  // throws TException
- (double) testDouble: (double) thing;  // throws TException
- (NSData *) testBinary: (NSData *) thing;  // throws TException
- (ThriftTestXtruct *) testStruct: (ThriftTestXtruct *) thing;  // throws TException
- (ThriftTestXtruct2 *) testNest: (ThriftTestXtruct2 *) thing;  // throws TException
- (NSMutableDictionary *) testMap: (NSMutableDictionary *) thing;  // throws TException
- (NSMutableDictionary *) testStringMap: (NSMutableDictionary *) thing;  // throws TException
- (NSMutableSet *) testSet: (NSMutableSet *) thing;  // throws TException
- (NSMutableArray *) testList: (NSMutableArray *) thing;  // throws TException
- (int) testEnum: (int) thing;  // throws TException
- (ThriftTestUserId) testTypedef: (ThriftTestUserId) thing;  // throws TException
- (NSMutableDictionary *) testMapMap: (int32_t) hello;  // throws TException
- (NSMutableDictionary *) testInsanity: (ThriftTestInsanity *) argument;  // throws TException
- (ThriftTestXtruct *) testMulti: (uint8_t) arg0 arg1: (int32_t) arg1 arg2: (int64_t) arg2 arg3: (NSMutableDictionary *) arg3 arg4: (int) arg4 arg5: (ThriftTestUserId) arg5;  // throws TException
- (void) testException: (NSString *) arg;  // throws ThriftTestXception *, TException
- (ThriftTestXtruct *) testMultiException: (NSString *) arg0 arg1: (NSString *) arg1;  // throws ThriftTestXception *, ThriftTestXception2 *, TException
- (void) testOneway: (int32_t) secondsToSleep;  // throws TException
@end

@interface ThriftTestThriftTestClient : NSObject <ThriftTestThriftTest> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ThriftTestThriftTestProcessor : NSObject <TProcessor> {
  id <ThriftTestThriftTest> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithThriftTest: (id <ThriftTestThriftTest>) service;
- (id<ThriftTestThriftTest>) service;
@end

@protocol ThriftTestSecondService <NSObject>
- (void) blahBlah;  // throws TException
- (NSString *) secondtestString: (NSString *) thing;  // throws TException
@end

@interface ThriftTestSecondServiceClient : NSObject <ThriftTestSecondService> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ThriftTestSecondServiceProcessor : NSObject <TProcessor> {
id <ThriftTestSecondService> mService;
NSDictionary * mMethodMap;
}
- (id) initWithSecondService: (id <ThriftTestSecondService>) service;
- (id<ThriftTestSecondService>) service;
@end

@interface ThriftTestThriftTestConstants : NSObject {
}
+ (int) myNumberz;
@end
